accent = "#684c59"
cursor = "#a87569"
foreground = "#e3a68c"
background = "#1c1213"
selection_foreground = "#f28171"
selection_background = "#684c59"

color0 = "#1c1213"
color1 = "#c24f57"
color2 = "#806c61"
color3 = "#f28171"
color4 = "#684c59"
color5 = "#a63650"
color6 = "#6b6566"
color7 = "#a87569"
color8 = "#6d4745"
color9 = "#c24f57"
color10 = "#806c61"
color11 = "#f28171"
color12 = "#684c59"
color13 = "#a63650"
color14 = "#6b6566"
color15 = "#e3a68c"
